config/routes.rb
Rails.application.routes.draw do
  get 'actors/new'
  get 'actors/create'
  devise_for :users
    resources :tv_shows do
       resources :episodes
       resources :actors, only: [:new, :create]
    end
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_one_attached :image
  has_and_belongs_to_many :tv_shows
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :tv_show
end

app/models/film_location.rb
class FilmLocation < ApplicationRecord
  belongs_to :tv_show
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_tv_shows
  has_many :tv_shows, through: :genre_tv_shows
end

app/models/genre_tv_show.rb
class GenreTvShow < ApplicationRecord
  belongs_to :genre
  belongs_to :tv_show
end

app/models/nationality.rb
class Nationality < ApplicationRecord
  has_many :tv_shows, dependent: :destroy
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  has_many :genre_tv_shows
  has_many :genres, through: :genre_tv_shows
  has_many :episodes, dependent: :destroy
  belongs_to :nationality
  has_many :film_locations,dependent: :destroy, inverse_of: :tv_show
  accepts_nested_attributes_for :film_locations
  belongs_to :user
  validates :name, presence: true
  has_and_belongs_to_many :actors
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tv_shows, dependent: :destroy
  has_one_attached :image
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def new
    @tv_show = TvShow.find(params[:tv_show_id])
    @actor = @tv_show.actors.build
  end

  def create
    @tv_show = TvShow.find(params[:tv_show_id])
        @actor = @tv_show.actors.create!(actor_params)
        redirect_to @tv_show
  end
  private

  def actor_params
      params.require(:actor).permit(:first_name, :last_name, :age)
  end

  def actor_params
    params.require(:actor).permit(:first_name, :last_name, :age, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def create
      @tv_show = TvShow.find(params[:tv_show_id])
      @episode = @tv_show.episodes.create(episode_params)
      redirect_to tv_show_path(@tv_show)
  end

  private
  def episode_params
      params.require(:episode).permit(:episode_number, :title, :summary)
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :set_tv_show, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index]

  # GET /tv_shows or /tv_shows.json
  def index
    @tv_shows = TvShow.all

  end

  # GET /tv_shows/1 or /tv_shows/1.json
  def show
  end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
    2.times { @tv_show.film_locations.build }
  end

  # GET /tv_shows/1/edit
  def edit
  end

  # POST /tv_shows or /tv_shows.json
  def create
    @tv_show = current_user.tv_shows.build(tv_show_params)
    @tv_show = TvShow.new(tv_show_params)
    @tv_show.nationality = Nationality.find(params[:tv_show][:nationality_id])
    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to tv_show_url(@tv_show), notice: "Tv show was successfully created." }
        format.json { render :show, status: :created, location: @tv_show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_shows/1 or /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to tv_show_url(@tv_show), notice: "Tv show was successfully updated." }
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1 or /tv_shows/1.json
  def destroy
    @tv_show.destroy

    respond_to do |format|
      format.html { redirect_to tv_shows_url, notice: "Tv show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tv_show_params
      params.require(:tv_show).permit(
      :name,
      :summary,
      :release_date,
      :rating,
      :nationality_id,
      film_locations_attributes: [:id, :name, :indoor],
      genre_ids: []
      )
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/actors/create.html.erb
<h1>Actors#create</h1>
<p>Find me in app/views/actors/create.html.erb</p>

app/views/actors/new.html.erb
<h1>Add actors to tv_show</h1>

<%= form_with(model:[@tv_show, @actor]) do |form| %>
    <div class="field">
        <%= form.label :first_name %>
        <%= form.text_field :first_name %>
    </div>

    <div class="field">
        <%= form.label :last_name %>
        <%= form.text_field :last_name %>
    </div>

    <div class="field">
        <%= form.label :age %>
        <%= form.number_field :age %>
    </div>

    <div class="field">
        <%= form.label :image %>
        <%= form.file_field :image %>
    </div>

    <br>
    <div class="field">
        <%= form.submit %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>MyFavoriteTvSeriesM9</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
    <br><br><br><br><br>
        <% if user_signed_in? %>
            <div class=bienvenidos>
                <p>Bienvenido <%= current_user.email %>!!</p>
                <button class=boton><%= link_to 'Log out', destroy_user_session_path, method: :delete %> </button>
            </div>
        <% else %>
            <div>
                <button class=boton><%= link_to 'Sign up', new_user_registration_path %> </button>
               <button class=boton><%= link_to 'Log in', new_user_session_path %> </button>
            </div>
        <% end %>
        <%= yield %>
    </body>
</html>

app/views/tv_shows/_form.html.erb
<%= form_with(model: tv_show) do |form| %>
  <% if tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>

      <ul>
        <% tv_show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
        <%= form.collection_check_boxes :genre_ids, Genre.all, :id, :name %>
    </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.datetime_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
        <%= collection_select(:tv_show, :nationality_id, Nationality.all, :id, :name, prompt: true) %>
    </div>

 <div class="field">
     <%= form.collection_select(:genre_ids, Genre.all, :id, :name,{ prompt: true }, { multiple: true }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tv_shows/edit.html.erb
<h1>Editing Tv Show</h1>
<div class=div>
<%= render 'form', tv_show: @tv_show %>
</div>
<div class=control>
<%= link_to 'Show', @tv_show %> |
<%= link_to 'Back', tv_shows_path %>
</div>

app/views/tv_shows/index.html.erb
  <div class="div">
    <p id="notice"><%= notice %></p>

    <h1 class="text-center">Tv Shows</h1>

    <table class="table table-bordered table-dark">
      <thead >
        <tr>
          <th>Name</th>
          <th>Summary</th>
          <th>Release date</th>
          <th>Rating</th>
          <th>nationaliti</th>
          <th colspan="3"></th>
        </tr>
      </thead>

    <tbody>
        <% @tv_shows.each do |tv_show| %>
        <tr>
          <td><%= tv_show.name %></td>
          <td><%= tv_show.summary %></td>
          <td><%= tv_show.release_date %></td>
          <td><%= tv_show.rating %></td>
          <td ><%= image_tag(url_for(tv_show.nationality.flag_img))  %></td>
          <td type="button" class="btn btn-outline-success"><%= link_to 'Show', tv_show %></td>
          <td type="button" class="btn btn-outline-info"><%= link_to 'Edit', edit_tv_show_path(tv_show) %></td>
          <td type="button" class="btn btn-outline-danger"><%= link_to 'Destroy', tv_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           <% if user_signed_in? %>
                    <td><%= link_to 'Show', tv_show %></td>
                <% end %>
                <% if (user_signed_in? && (current_user == tv_show.user)) %>
                    <td><%= link_to 'Edit', edit_tv_show_path(tv_show) %></td>
                    <td><%= link_to 'Destroy', tv_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
<br>
<div class="d-flex justify-content-center">
<button type="button" class="btn btn-secondary"><%= link_to 'New Tv Show', new_tv_show_path %></button>
</div>

app/views/tv_shows/new.html.erb
<h1>New Tv Show</h1>
<div class=div>
<%= render 'form', tv_show: @tv_show %>
</div>
<div class=control>
<%= link_to 'Back', tv_shows_path %>
</div>

app/views/tv_shows/show.html.erb
<div class=div>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tv_show.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @tv_show.summary %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @tv_show.release_date %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @tv_show.rating %>
</p>
<br>
<p>
    <strong>Nationality:</strong>
    <%= image_tag(url_for(@tv_show.nationality.flag_img)) %>
</p>
</div>
<br>
<div class=div>
<h2>Listado de episodios</h2>
<% @tv_show.episodes.each do |episode| %>
    <p>
        <strong>Episode number:</strong>
        <%= episode.episode_number %>
    </p>

    <p>
        <strong>Title:</strong>
        <%= episode.title %>
    </p>

    <p>
        <strong>Summary:</strong>
        <%= episode.summary %>
    </p>
<% end %>
</div>
<div class=div>
<h2>Agregue un episodio:</h2>
<%= form_with model: [ @tv_show, @tv_show.episodes.build ] do |form| %>
    <p>
        <%= form.label :episode_number %><br>
        <%= form.number_field :episode_number %>
    </p>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :summary %><br>
        <%= form.text_area :summary %>
    </p>
    <p>
        <%= form.submit "Crear episodio"%>
    </p>
<% end %>
</div>

<div class=div>
<p><strong>Actors:</strong></p>
<ul>
    <% if @tv_show.actors %>
        <% @tv_show.actors.each do |actor|%>
            <li><strong><%= actor.id %>: </strong><%= "#{actor.first_name} #{actor.last_name}" %></li>
            <% if actor.image.attached? %>
                <li><%= image_tag(actor.image, size: '50x50') %></li>
            <% end %>
        <% end %>
    <% else %>
        <% 'No Actors Added!!!'%>
    <% end %>
</ul>
  <div class=divactores>
    <button class=boton><%= link_to 'Add actors', new_tv_show_actor_path(@tv_show) %> </button>
  </div>
</div>

<div class=div>
<p><strong>Genres:</strong></p>
<ul>
    <% if @tv_show.genres %>
        <% @tv_show.genres.each do |genre|%>
            <li><strong><%= "#{genre.id}" %>: </strong><%= genre.name %></li>
        <% end %>
    <% else %>
        <% 'No Genres Added!!!'%>
    <% end %>
</ul>


</div>




<div class=control>
<button class=boton><%= link_to 'Edit', edit_tv_show_path(@tv_show) %> </button>
<button class=boton><%= link_to 'Back', tv_shows_path %></button>
</div>